author: Rayzs_YT

name: IronGolemsCanBuild
description: Allows iron golems to build up to players.

main: de.rayzs.igcb.IGCBPluginLoader

version: ${projectVersion}
api-version: 1.13

folia-supported: true